import { writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const packageJsonPath = join(__dirname, '../package.json');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));

const version = packageJson.version;

const targetPath = join(__dirname, '../src/environments/version.ts');
const content = `// This file is auto-generated by scripts/version.ts
export const appVersion = '${version}';
`;

writeFileSync(targetPath, content, { encoding: 'utf8' });